apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fuenfgiebel
  namespace: fuenfgiebel
  labels:
    app.kubernetes.io/name: fuenfgiebel
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: public
  rules:
    - host: fuenfgiebel.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fuenfgiebel
                port:
                  name: http
    - host: www.fuenfgiebel.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fuenfgiebel
                port:
                  name: http
  # TLS configuration
  tls:
    - hosts:
        - fuenfgiebel.de
        - www.fuenfgiebel.de
      secretName: fuenfgiebel-tls
